# Generated by Django 4.1.2 on 2023-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0014_auto_20220624_1455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
