# Generated by Django 4.2.3 on 2023-07-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-create_time',), 'verbose_name_plural': '话题管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
    ]
